Repository PlasmNetwork/lockdrop-ui, pull requests merged in 2020-07, with the labels that each got.

#62 Add/btc trezor support
  package.json
  src/components/BtcLock/BtcRawSignature.tsx
  src/components/BtcLock/QrEncodedAddress.tsx
  src/components/BtcLock/TrezorLock.tsx
  src/components/EthLock/LockdropForm.tsx
  src/components/LockdropCountdownPanel.tsx
  src/components/SideMenu.tsx
  src/helpers/lockdrop/BitcoinLockdrop.ts
  src/pages/DustyBtcLockPage.tsx
  src/tests/btcLock.test.ts
  yarn.lock
Labels: enhancement

#68 Fix/eth instance divide
  package.json
  src/data/lockInfo.ts
  src/helpers/lockdrop/EthereumLockdrop.ts
  src/helpers/plasmUtils.ts
  src/pages/DustyEthLockPage.tsx
  src/pages/EthLockdropPage.tsx
  src/tests/plasmLock.test.ts
  yarn.lock
Labels: enhancement

#65 Fix/lock claim request
  package.json
  src/components/BtcLock/BtcRawSignature.tsx
  src/components/BtcLock/LockStatus.tsx
  src/components/BtcLock/TrezorLock.tsx
  src/helpers/lockdrop/BitcoinLockdrop.ts
  src/helpers/plasmUtils.ts
  src/pages/DustyBtcLockPage.tsx
  src/pages/DustyEthLockPage.tsx
  src/tests/btcLock.test.ts
  src/tests/plasmLock.test.ts
  src/types/LockdropModels.ts
  tsconfig.json
  yarn.lock
Labels: bug

#63 Fix/audit report
  src/App.tsx
  src/components/BtcLock/BtcRawSignature.tsx
  src/components/BtcLock/LockStatus.tsx
  src/components/BtcLock/TrezorLock.tsx
  src/components/CopyMessageBox.tsx
  src/data/lockInfo.ts
  src/helpers/lockdrop/BitcoinLockdrop.ts
  src/pages/DustyBtcLockPage.tsx
  src/tests/btcLock.test.ts
  src/types/LockdropModels.ts
Labels: bug, enhancement
